language: php
os: linux

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION='4.3.*'
    - php: 7.2
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.3
      env: SYMFONY_VERSION='5.0.*'
  allow_failures:
    - php: nightly

before_script:
  - |
    if [ "$SYMFONY_VERSION" != "" ]; then
      sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
    fi;
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
  - composer install --dev --no-interaction
  - ./vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml $PHPUNIT_FLAGS

after_success:
  - travis_retry php ./vendor/bin/php-coveralls
